#!/bin/bash
#
# Temporary solution allowing direct using the built binary.
#

# Remove an existing soft link
rm ~/.local/bin/lsgit2

# Create a new soft link
ln -s $PWD/target/release/lsgit2 ~/.local/bin/lsgit2

# List the directrory to make sure that the link is there
ls -la ~/.local/bin/lsg*
